// WITHOUT redux-thunk pattern
// const ShopTypes = {
//   UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
// };

// WITH redux-thunk pattern
const ShopTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
};

export default ShopTypes;
